"""
Communication Agent - drafts three ready-to-send, professional client
messages (BILL IT / NEGOTIATE IT / DECLINE IT) for a given request, so the
freelancer can just pick one and send it. Messages are generated by the
LLM, not templated/hard-coded strings.
"""

from __future__ import annotations

from strands import Agent

from models.scope_models import GeneratedMessages, ScopeAnalysisResult, StatementOfWork

SYSTEM_PROMPT_TEMPLATE = """You are the Communication Agent for a freelancer working on
"{project_name}" (hourly rate: ${hourly_rate}/hour).

Given a client's request and how it was classified against the SOW, write
three short, professional, client-facing messages - one for each path the
freelancer might choose:

- bill_it: Frame the request as a reasonable add-on, mention the estimated
  extra hours and cost, and offer to proceed once approved.
- negotiate_it: Open a conversation about scope/timeline trade-offs without
  committing to a price yet.
- decline_it: Politely explain it's outside the current phase's scope
  without sounding unhelpful - leave the door open for a future phase.

Keep each message to 2-4 sentences, friendly but professional. Do not
invent SOW details you weren't given."""


class CommunicationAgent:
    def __init__(self, model, sow: StatementOfWork):
        self._agent = Agent(
            model=model,
            system_prompt=SYSTEM_PROMPT_TEMPLATE.format(
                project_name=sow.project_name, hourly_rate=sow.hourly_rate
            ),
        )

    def draft_messages(
        self,
        request_text: str,
        analysis: ScopeAnalysisResult,
        estimated_cost: float,
    ) -> GeneratedMessages:
        prompt = (
            f'Client request: "{request_text}"\n'
            f"Classification: {analysis.classification.value}\n"
            f"Reason: {analysis.reasoning}\n"
            f"Estimated extra effort: {analysis.estimated_hours} hours "
            f"(~${estimated_cost:.2f})."
        )
        return self._agent.structured_output(GeneratedMessages, prompt)